---
title: "Dora Analysis"
author: "doraaobodo"
date: "2021-12-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

## Load data

Load data example here.

```{r load libraries}
library(data.table)
library(ggplot2)
library(workflowr)
```



```{r load all data}
movieDT = fread('data/MoviesOnStreamingPlatforms_updated.csv')
movieDT = movieDT[,-c('V1')]
head(movieDT, 5)
```

## extract numeric values from IMDb and Rotten Tomatoes
```{r}
movieDT[, imdb_num := as.numeric(
  gsub(pattern="\\/(.*)", replacement="", IMDb, perl = TRUE))]

movieDT[, tomatoe_num := as.numeric(
  gsub(pattern="\\/(.*)", replacement="", `Rotten Tomatoes`, perl = TRUE))]
``` 

### Are rating scores correlated to each other on each platform?

```{r scatter of platform}
movieDT = melt(movieDT, measure.vars = c("Netflix","Hulu","Prime Video","Disney+"), 
               variable.name = 'platform')
movieDT = movieDT[value == 1]
ggplot(movieDT, aes(x = imdb_num, y = tomatoe_num)) + geom_point() + facet_wrap(~platform)
```


### Which Genre of movies tend to score higher per platform
```{r scatter of movies}
countGenres = movieDT[, .N, by = .(platform, Genres)]
countGenres = countGenres[N > 50]
ggplot(countGenres, aes(x = platform, y = N)) + geom_bar(stat = 'identity') + facet_wrap(~Genres)

```
